# Generated by Django 6.0.1 on 2026-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monkey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                ("is_active", models.BooleanField(verbose_name="Is active?")),
                ("balance", models.IntegerField(verbose_name="Cash balance")),
            ],
        ),
    ]
