# Generated by Django 6.0.1 on 2026-06-05 14:46

import django.core.validators
from django.db import migrations, models


def copy_balance_to_initial_balance(apps, schema_editor):
    Monkey = apps.get_model("monkey", "Monkey")
    for monkey in Monkey.objects.all():
        monkey.initial_balance = monkey.balance
        monkey.save(update_fields=["initial_balance"])


class Migration(migrations.Migration):
    dependencies = [
        ("monkey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalMonkeyControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False, verbose_name="Is monkey trading enabled?"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=256, verbose_name="Note"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KisAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Environment"
                    ),
                ),
                ("token", models.TextField(verbose_name="Access token")),
                ("expires_at", models.DateTimeField(verbose_name="Expires at")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="monkey",
            name="initial_balance",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Initial cash balance",
            ),
        ),
        migrations.RunPython(
            copy_balance_to_initial_balance,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="monkey",
            name="max_quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Maximum order quantity",
            ),
        ),
        migrations.AddField(
            model_name="monkey",
            name="min_quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Minimum order quantity",
            ),
        ),
        migrations.AlterField(
            model_name="monkey",
            name="balance",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Cash balance",
            ),
        ),
        migrations.AlterField(
            model_name="monkey",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active?"),
        ),
        migrations.AddConstraint(
            model_name="monkey",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_quantity__gte", 1)),
                name="monkey_min_quantity_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="monkey",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_quantity__gte", models.F("min_quantity"))),
                name="monkey_max_quantity_gte_min_quantity",
            ),
        ),
    ]
