# Generated by Django 6.0.1 on 2026-06-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monkey", "0002_globalmonkeycontrol_kisaccesstoken_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonkeyDailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Snapshot date")),
                ("cash_balance", models.IntegerField(verbose_name="Cash balance")),
                ("holdings_value", models.IntegerField(verbose_name="Holdings value")),
                ("total_equity", models.IntegerField(verbose_name="Total equity")),
                ("total_pl", models.IntegerField(verbose_name="Total P&L")),
                ("realized_pl", models.IntegerField(verbose_name="Realized P&L")),
                ("unrealized_pl", models.IntegerField(verbose_name="Unrealized P&L")),
                ("earning_ratio", models.FloatField(verbose_name="Earning ratio")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "monkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_snapshots",
                        to="monkey.monkey",
                        verbose_name="monkey",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "monkey_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("monkey", "date"),
                        name="unique_snapshot_per_monkey_date",
                    )
                ],
            },
        ),
    ]
