# Generated by Django 6.0.1 on 2026-06-12 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monkey", "0007_schedule_market_hours_tasks"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="monkey",
            name="monkey_min_quantity_gte_1",
        ),
        migrations.RemoveConstraint(
            model_name="monkey",
            name="monkey_max_quantity_gte_min_quantity",
        ),
        migrations.RemoveField(
            model_name="globalmonkeycontrol",
            name="order_interval_seconds",
        ),
        migrations.AddField(
            model_name="monkey",
            name="order_interval_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="How often this monkey places a random order.",
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(1800),
                ],
                verbose_name="Order interval (seconds)",
            ),
        ),
        migrations.RemoveField(
            model_name="monkey",
            name="max_quantity",
        ),
        migrations.RemoveField(
            model_name="monkey",
            name="min_quantity",
        ),
    ]
