# Generated by Django 6.0.1 on 2026-06-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monkey", "0009_randomize_monkey_intervals"),
    ]

    operations = [
        migrations.AddField(
            model_name="monkey",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Hidden monkey used to absorb/liquidate orphaned real-account positions.",
                verbose_name="Is system monkey?",
            ),
        ),
    ]
