# Generated by Django 6.0.1 on 2026-06-12 17:51

from django.db import migrations, models

TASK_NAME = "monkey.earning_ratio_tick"


def create_schedule(apps, schema_editor):
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    interval, _ = IntervalSchedule.objects.get_or_create(
        every=60,
        period="seconds",
    )
    PeriodicTask.objects.get_or_create(
        name=TASK_NAME,
        defaults={
            "task": "monkey.tasks.record_earning_ratio_tick",
            "interval": interval,
            "enabled": True,
        },
    )


def remove_schedule(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name=TASK_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("monkey", "0012_schedule_auto_create_monkeys"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonkeyEarningRatioTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Recorded at"
                    ),
                ),
                (
                    "average_earning_ratio",
                    models.FloatField(verbose_name="Average earning ratio"),
                ),
            ],
            options={
                "ordering": ["recorded_at"],
            },
        ),
        migrations.RunPython(create_schedule, remove_schedule),
    ]
