# Generated by Django 6.0.1 on 2026-06-15 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monkey", "0019_reconcile_daily_and_skip_expire"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalmonkeycontrol",
            name="auto_create_max_interval_seconds",
            field=models.PositiveIntegerField(
                default=1800,
                help_text="Upper bound of the random order interval assigned to newly created monkeys.",
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(1800),
                ],
                verbose_name="New monkey max order interval (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="globalmonkeycontrol",
            name="auto_create_min_interval_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Lower bound of the random order interval assigned to newly created monkeys.",
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(1800),
                ],
                verbose_name="New monkey min order interval (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="globalmonkeycontrol",
            name="auto_create_starting_balance",
            field=models.PositiveIntegerField(
                default=1000000,
                help_text="Cash each monkey is created with (auto-create divides unallocated cash by this).",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Auto-create starting balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="globalmonkeycontrol",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "auto_create_max_interval_seconds__gte",
                        models.F("auto_create_min_interval_seconds"),
                    )
                ),
                name="globalcontrol_interval_max_gte_min",
            ),
        ),
    ]
