# Generated by Django 6.0.1 on 2026-06-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monkey", "0021_schedule_system_monkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonkeyIndexBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Trading date")),
                (
                    "base_index",
                    models.FloatField(verbose_name="Base index (yesterday's close)"),
                ),
                (
                    "base_equity",
                    models.BigIntegerField(
                        verbose_name="Base equity (alive monkeys at open)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="MonkeyIndexTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Recorded at"
                    ),
                ),
                ("value", models.FloatField(verbose_name="Index value")),
            ],
            options={
                "ordering": ["recorded_at"],
            },
        ),
        migrations.DeleteModel(
            name="MonkeyEarningRatioTick",
        ),
    ]
