# Generated by Django 6.0.1 on 2026-06-16 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monkey", "0023_rename_index_and_maintenance_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalmonkeycontrol",
            name="auto_create_max_interval_seconds",
            field=models.PositiveIntegerField(
                default=1800,
                help_text="Upper bound of the random order interval assigned to newly created monkeys.",
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(7200),
                ],
                verbose_name="New monkey max order interval (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="globalmonkeycontrol",
            name="auto_create_min_interval_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Lower bound of the random order interval assigned to newly created monkeys.",
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(7200),
                ],
                verbose_name="New monkey min order interval (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="monkey",
            name="order_interval_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="How often this monkey places a random order.",
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(7200),
                ],
                verbose_name="Order interval (seconds)",
            ),
        ),
    ]
