# Generated by Django 6.0.1 on 2026-06-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "monkey",
            "0024_alter_globalmonkeycontrol_auto_create_max_interval_seconds_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="KisAccountCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Environment"
                    ),
                ),
                ("cash_balance", models.IntegerField(verbose_name="Cash balance")),
                (
                    "securities_value",
                    models.IntegerField(verbose_name="Securities value"),
                ),
                ("total_assets", models.IntegerField(verbose_name="Total assets")),
                ("total_pl", models.IntegerField(verbose_name="Total P&L")),
                ("earning_rate", models.FloatField(verbose_name="Earning rate")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
        ),
    ]
