# Generated by Django 6.0.1 on 2026-06-17 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import monkey.fields


def delete_stale_token_cache(apps, schema_editor):
    """The token/cache were keyed by an ``environment`` string and predate any
    Account row. They can't be re-pointed, so drop them — tokens refresh lazily
    and the balance cache rebuilds on the first poll once accounts are registered.
    """
    apps.get_model("monkey", "KisAccessToken").objects.all().delete()
    apps.get_model("monkey", "KisAccountCache").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("monkey", "0027_wipe_index_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("mock", "모의투자"), ("real", "실전투자")],
                        default="mock",
                        max_length=8,
                        verbose_name="Account type",
                    ),
                ),
                ("app_key", monkey.fields.EncryptedTextField(verbose_name="App key")),
                (
                    "app_secret",
                    monkey.fields.EncryptedTextField(verbose_name="App secret"),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="8-digit KIS account number, no hyphens.",
                        max_length=16,
                        verbose_name="Account number (CANO)",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        default="01", max_length=4, verbose_name="Account product code"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-delete flag; inactive accounts keep their history but no longer trade.",
                        verbose_name="Is active?",
                    ),
                ),
                (
                    "auto_create_starting_balance",
                    models.PositiveIntegerField(
                        default=1000000,
                        help_text="Cash each monkey on this account is created with.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Auto-create starting balance",
                    ),
                ),
                (
                    "auto_create_min_interval_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Fastest cadence (haste=1) for this account's monkeys.",
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(7200),
                        ],
                        verbose_name="Min order interval (seconds)",
                    ),
                ),
                (
                    "auto_create_max_interval_seconds",
                    models.PositiveIntegerField(
                        default=1800,
                        help_text="Slowest cadence (haste=0) for this account's monkeys.",
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(7200),
                        ],
                        verbose_name="Max order interval (seconds)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="globalmonkeycontrol",
            name="globalcontrol_interval_max_gte_min",
        ),
        migrations.RemoveField(
            model_name="kisaccesstoken",
            name="environment",
        ),
        migrations.RemoveField(
            model_name="kisaccountcache",
            name="environment",
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("account_number", "product_code"),
                name="unique_account_cano_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "auto_create_max_interval_seconds__gte",
                        models.F("auto_create_min_interval_seconds"),
                    )
                ),
                name="account_interval_max_gte_min",
            ),
        ),
        # Drop the legacy environment-keyed rows, then add the account FK against
        # the now-empty tables (nullable add → alter to non-null, no bogus default).
        migrations.RunPython(delete_stale_token_cache, migrations.RunPython.noop),
        migrations.AddField(
            model_name="kisaccesstoken",
            name="account",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_token",
                to="monkey.account",
                verbose_name="account",
            ),
        ),
        migrations.AddField(
            model_name="kisaccountcache",
            name="account",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_cache",
                to="monkey.account",
                verbose_name="account",
            ),
        ),
        migrations.AlterField(
            model_name="kisaccesstoken",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_token",
                to="monkey.account",
                verbose_name="account",
            ),
        ),
        migrations.AlterField(
            model_name="kisaccountcache",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_cache",
                to="monkey.account",
                verbose_name="account",
            ),
        ),
        migrations.AddField(
            model_name="monkey",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="The KIS account this monkey trades on (mock only). Null once orphaned.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monkeys",
                to="monkey.account",
                verbose_name="account",
            ),
        ),
        migrations.AddConstraint(
            model_name="monkey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", False), ("is_system", True)),
                fields=("account",),
                name="unique_system_monkey_per_account",
            ),
        ),
        migrations.RemoveField(
            model_name="globalmonkeycontrol",
            name="auto_create_max_interval_seconds",
        ),
        migrations.RemoveField(
            model_name="globalmonkeycontrol",
            name="auto_create_min_interval_seconds",
        ),
        migrations.RemoveField(
            model_name="globalmonkeycontrol",
            name="auto_create_starting_balance",
        ),
    ]
