# Generated by Django 6.0.1 on 2026-06-18 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monkey", "0030_schedule_finalize_filled_orders"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="account_interval_max_gte_min",
        ),
        migrations.AddField(
            model_name="globalmonkeycontrol",
            name="auto_create_max_interval_seconds",
            field=models.PositiveIntegerField(
                default=1800,
                help_text="Slowest possible cadence (haste=0). The haste trait interpolates the order interval across this min..max range.",
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(7200),
                ],
                verbose_name="Max order interval (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="globalmonkeycontrol",
            name="auto_create_min_interval_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Fastest possible cadence (haste=1). The haste trait interpolates the order interval across this min..max range.",
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(7200),
                ],
                verbose_name="Min order interval (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="globalmonkeycontrol",
            name="auto_create_starting_balance",
            field=models.PositiveIntegerField(
                default=1000000,
                help_text="Cash each monkey is created with (auto-create divides unallocated cash by this).",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Auto-create starting balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="globalmonkeycontrol",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "auto_create_max_interval_seconds__gte",
                        models.F("auto_create_min_interval_seconds"),
                    )
                ),
                name="globalcontrol_interval_max_gte_min",
            ),
        ),
        migrations.RemoveField(
            model_name="account",
            name="auto_create_max_interval_seconds",
        ),
        migrations.RemoveField(
            model_name="account",
            name="auto_create_min_interval_seconds",
        ),
        migrations.RemoveField(
            model_name="account",
            name="auto_create_starting_balance",
        ),
    ]
