# Generated by Django 6.0.1 on 2026-06-14 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "버그 신고"),
                            ("feature", "기능 제안"),
                            ("general", "일반 의견"),
                            ("other", "기타"),
                        ],
                        default="general",
                        max_length=32,
                        verbose_name="Category",
                    ),
                ),
                ("subject", models.CharField(max_length=256, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "신규"), ("answered", "답변 완료")],
                        default="new",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reply_message",
                    models.TextField(blank=True, verbose_name="Reply message"),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Replied at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "replied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Replied by",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
