# Generated by Django 6.0.1 on 2026-04-23 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("monkey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market",
                    models.CharField(max_length=32, verbose_name="Stock market"),
                ),
                (
                    "ticker",
                    models.CharField(max_length=16, verbose_name="Stock ticker"),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Stock name")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.IntegerField(
                        choices=[(0, "Buy"), (1, "Sell")], verbose_name="Order type"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Execution price")),
                ("quantity", models.IntegerField(verbose_name="Executed quantity")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.stock",
                        verbose_name="stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity held")),
                (
                    "monkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monkey.monkey",
                        verbose_name="monkey",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.stock",
                        verbose_name="stock",
                    ),
                ),
            ],
        ),
    ]
