# Generated by Django 6.0.1 on 2026-01-29 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
        ("monkey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity held")),
                (
                    "monkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monkey.monkey",
                        verbose_name="monkey",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.stock",
                        verbose_name="stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.IntegerField(
                        choices=[(0, "Buy"), (1, "Sell")], verbose_name="Order type"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Execution price")),
                ("quantity", models.IntegerField(verbose_name="Executed quantity")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.stock",
                        verbose_name="stock",
                    ),
                ),
            ],
        ),
    ]
