# Generated by Django 6.0.1 on 2026-04-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("ticker", "market"), name="unique_ticker_per_market"
            ),
        ),
    ]
