# Generated by Django 6.0.1 on 2026-06-05 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def mark_legacy_orders_succeeded(apps, schema_editor):
    Order = apps.get_model("market", "Order")
    for order in Order.objects.all():
        order.executed_quantity = order.requested_quantity
        order.executed_price = order.estimated_price
        order.status = "succeeded"
        order.save(
            update_fields=[
                "executed_quantity",
                "executed_price",
                "status",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_stock_unique_ticker_per_market"),
        ("monkey", "0002_globalmonkeycontrol_kisaccesstoken_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="price",
            new_name="estimated_price",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="quantity",
            new_name="requested_quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="estimated_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Estimated price"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="executed_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Execution price"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="executed_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Executed quantity"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="failure_reason",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Failure reason"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="kis_order_id",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="KIS order ID"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="kis_order_status",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="KIS order status"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="kis_request",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="KIS request"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="kis_response",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="KIS response"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="monkey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="monkey.monkey",
                verbose_name="monkey",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="requested_quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Requested quantity",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("skipped", "Skipped"),
                    ("submitted", "Submitted"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.RunPython(
            mark_legacy_orders_succeeded,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="holding",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity held",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="market.stock",
                verbose_name="stock",
            ),
        ),
        migrations.AddConstraint(
            model_name="holding",
            constraint=models.UniqueConstraint(
                fields=("monkey", "stock"), name="unique_holding_per_monkey_stock"
            ),
        ),
    ]
