# Generated by Django 6.0.1 on 2026-06-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0003_remove_order_price_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this stock is currently listed on its market.",
                verbose_name="Is active?",
            ),
        ),
    ]
