# Generated by Django 6.0.1 on 2026-06-16 18:42

from django.db import migrations, models


def backfill_short_code(apps, schema_editor):
    Stock = apps.get_model("market", "Stock")
    to_update = []
    for stock in Stock.objects.all().only("id", "ticker", "short_code"):
        short_code = (stock.ticker or "")[-6:]
        if stock.short_code != short_code:
            stock.short_code = short_code
            to_update.append(stock)
    if to_update:
        Stock.objects.bulk_update(to_update, ["short_code"])


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0005_stock_current_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="short_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Last 6 digits of the ticker (prefix stripped). KIS balance inquiries return holdings by this 6-digit code, so reconciliation joins on it.",
                max_length=6,
                verbose_name="Short code",
            ),
        ),
        migrations.RunPython(backfill_short_code, migrations.RunPython.noop),
    ]
