# Generated by Django 6.0.1 on 2026-06-16 18:54

from django.db import migrations, models


def rebackfill_short_code(apps, schema_editor):
    # KIS strips the leading prefix only when the ticker is longer than 6 chars
    # (e.g. "J0669721F" -> "0669721F"); 0006 used the wrong last-6-digits rule.
    Stock = apps.get_model("market", "Stock")
    to_update = []
    for stock in Stock.objects.all().only("id", "ticker", "short_code"):
        ticker = stock.ticker or ""
        short_code = ticker[1:] if len(ticker) > 6 else ticker
        if stock.short_code != short_code:
            stock.short_code = short_code
            to_update.append(stock)
    if to_update:
        Stock.objects.bulk_update(to_update, ["short_code"])


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0006_stock_short_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="short_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Ticker with its leading prefix stripped when longer than 6 chars. KIS balance inquiries return holdings (pdno) by this code, so reconciliation joins on it.",
                max_length=16,
                verbose_name="Short code",
            ),
        ),
        migrations.RunPython(rebackfill_short_code, migrations.RunPython.noop),
    ]
