# Generated by Django 6.0.1 on 2026-06-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0007_alter_stock_short_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("skipped", "Skipped"),
                    ("submitted", "Submitted"),
                    ("executed", "Executed"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
