# Generated by Django 6.0.1 on 2026-06-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0009_succeeded_orders_to_executed"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="execution_detail",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Raw KIS daily-ccld output1 fill record captured at confirmation.",
                verbose_name="Execution detail",
            ),
        ),
    ]
