# Generated by Django 6.0.1 on 2026-06-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0010_order_execution_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="last_finalize_check",
            field=models.DateTimeField(
                blank=True,
                help_text="When the mid-session finalize pass last queried this SUBMITTED order's fill. Used to round-robin so one perpetually-partial order can't starve the rest of the queue.",
                null=True,
                verbose_name="Last finalize check",
            ),
        ),
    ]
